### ISSUE TITLE
[macOS Beta] Build: Fails to build with openMP error

### ISSUE THREAD

**Issue by shinra-electric** [Wargus/stratagus#702]
I tried to compile Stratagus today, and encountered a build error: 

`c++: error: unknown argument: '-Xclang -fopenmp'`

I should note that I'm on the macOS 15 public beta and Xcode 16 beta 4, as it may be relevant. 
However the last time I successfully built was on the 14th of July (on a previous beta) so it may not be the issue. 

Here is the full log: 
 
[Terminal Saved Output.txt](https://github.com/user-attachments/files/16431824/Terminal.Saved.Output.txt)

**Comment by Jarod42** [comment]
Turning CMake option `WITH_OPENMP` `OFF` would help (`cmake -DWITH_OPENMP=OFF [..]`)
Not sure if it is sufficient.
Tried to create [macos CI](https://github.com/Wargus/stratagus/blob/CI_macos/.github/workflows/macos.yml) , but it currently fails (libpng issue :/ ) before your issue :-/
I don't have MacOS, so using CI for experiment is not ideal.
If you can share the list of your pre-installed dependencies

**Comment by shinra-electric** [comment]
> Turning CMake option `WITH_OPENMP` `OFF` would help (`cmake -DWITH_OPENMP=OFF [..]`) Not sure if it is sufficient. 

That helps the build to complete, however it fails to launch with an error message about missing data. My data folders are in `Application Support/stratagus` and my build of War1gus from a few weeks ago still opens so it's not a data issue (unless extraction has changed recently).

>Tried to create [macos CI](https://github.com/Wargus/stratagus/blob/CI_macos/.github/workflows/macos.yml) , but it currently fails (libpng issue :/ ) before your issue :-/ I don't have MacOS, so using CI for experiment is not ideal. If you can share the list of your pre-installed dependencies

My installed homebrew libraries are:
`cmake dylibbundler sdl2 sdl2_mixer sdl2_image lua libpng ffmpeg meson ninja`
I don't see OpenMP on homebrew...

I you want to have a look at my build script, I have it [here](https://github.com/shinra-electric/Stratagus-Build-Script).

**Comment by Jarod42** [comment]
Does `stratagus --help` work?
Which flags do you provide to stratagus (`-d datadir`)? Which is the output of log (possibly stderr.txt stdout.txt)?


data by itself didn't change, script might (I don't think there was a change since several weeks for war1gus though)

**Comment by shinra-electric** [comment]
>  Which flags do you provide to stratagus (`-d datadir`)? 

I didn't provide any datadir flags. On macOS it automatically looks in Application Support (see #435). (I build an application bundle, so I usually don't run from Terminal). 

>Which is the output of log (possibly stderr.txt stdout.txt)?

A log wasn't saved, but here is the terminal output:
[Terminal Saved Output.txt](https://github.com/user-attachments/files/16444812/Terminal.Saved.Output.txt)
I noted that it's referencing files in the stratagus source folder. However, the source folder is deleted by my script after the app bundle is created. 
(This seems to be the same behaviour as [issue 438](https://github.com/Wargus/wargus/issues/438), where wartool references the source folders). 
I tried leaving the stratagus source folder intact, but it still crashed the same way. 

Here is a terminal log from my previous working build for your reference: 
[Terminal Saved Output(working).txt](https://github.com/user-attachments/files/16444877/Terminal.Saved.Output.working.txt)
 
Here are the error dialogs: 

<img width="532" alt="Screenshot 2024-07-31 at 17 36 22" src="https://github.com/user-attachments/assets/3b7e1b5c-e370-4c10-9392-d83d704da0f3">
<img width="532" alt="Screenshot 2024-07-31 at 17 36 53" src="https://github.com/user-attachments/assets/d5102c2f-1838-4dfd-879e-46046b9daa7b">

**Comment by shinra-electric** [comment]
> _"Unsupported key: Iterations"_ That is indeed a recent change :-) 
Overwrite script directory ("data.War1gus\scripts") with a recent one (or do a full extraction). 

I tried building again and re-extracted the game data. 

Here is the terminal output: 
[Terminal Saved Output.txt](https://github.com/user-attachments/files/16445428/Terminal.Saved.Output.txt)

Again, it's referencing files in the source folder that no longer exists.

**Comment by Jarod42** [comment]
> LoadMusic: Can't load the music 'music/23.mid'
> GetFileContent: Can't open file 'campaigns/orc/01_prerun.lua': No such file or directory
Not critical

> double free for ptr 0x1483b8000

Critical, and probably my fault with my recent changes in the engine.
Investigating.

**Comment by Jarod42** [comment]
https://github.com/Wargus/stratagus/pull/705 should fix the crashing issue (I didn't use the DYNAMIC_LOADING option, so I miss it)

**Comment by shinra-electric** [comment]
Both Wargus and War1gus are working again now, thanks. 

I still get a crash on exit with War1gus, but I think that's a different issue so I'll close this one.
